	Select * From Openquery(orad,
		'
		SELECT 
			QNOT_PLNT_ID, QNOT_TYP, QNOT_NO, QNDF_NO, QNOT_CREATED_DT, SERIAL_NUMBER, QNOT_ACT_END_DT, QNOT_EMPL_ID, QNOT_PART_NO, PartDesc, 
			QNOT_ORDR_NO, WBSE_CD, WBSE_DESC, QNOT_QNCT_TIER3_CD, QNCT_TIER2_DESC, QNDF_TYPE_QNCT_TIER3_CD, QNCT_TIER3_DESC, QNDF_DESC, QNDF_COMP_PART_NO, 
			RemPartDesc, QNDF_SPRT_SER_NO , WCTR_CD, WCTR_DESC, WCTR_WCCT_ID, OROP_ID, OROP_LINE1_DESC, QNTK_NO, QNTK_COMPLETED_DT, 
			QNTK_QNCT_TIER3_CD, Hours, QNDF_LOCN_QNCT_TIER3_CD, NOTE_TXT, ORDR_OPER_COMPLETED_DT, ORDR_STAT, ORDR_OCAT_CD

		FROM
			(
			select 
				QNOT_PLNT_ID, QNOT_TYP, QNOT_NO, QNDF_NO, QNOT_CREATED_DT, QNOT_ACT_END_DT, QNOT_EMPL_ID, QNOT_PART_NO, PART1.PART_DESC as PartDesc, 
				QNOT_ORDR_NO, QNOT_SPRT_SER_NO, WBSE_CD, WBSE_DESC, QNOT_QNCT_TIER3_CD, QNCT_TIER2_DESC, QNDF_TYPE_QNCT_TIER3_CD, QNCT_TIER3_DESC, 
				QNDF_DESC, QNDF_COMP_PART_NO, PART2.PART_DESC as RemPartDesc, QNDF_SPRT_SER_NO , WCTR_CD, WCTR_DESC, WCTR_WCCT_ID, OROP_ID, OROP_LINE1_DESC,
				QNTK_NO, QNTK_COMPLETED_DT, QNTK_QNCT_TIER3_CD,sum(QNDT_ACTUAL_HRS) AS Hours, QNDF_LOCN_QNCT_TIER3_CD, 
				trim(leading 0 from ORDR_SPRT_SER_NO) SERIAL_NUMBER, ORDR_OPER_COMPLETED_DT, ORDR_STAT, ORDR_OCAT_CD

			FROM TDWHQNOT
				LEFT JOIN TDWHQNDF ON QNDF_QNOT_NO = QNOT_NO 
				LEFT JOIN TDWHOROP ON QNDF_OROP_NO = OROP_NO AND QNDF_ORDR_RTG_NO = OROP_ORDR_RTG_NO 
				LEFT JOIN TDWHWCTR ON QNOT_WCTR_NO = WCTR_NO 
				LEFT JOIN TDWHQNCT ON QNDF_TYPE_QNCT_TIER3_CD = QNCT_TIER3_CD AND QNDF_TYPE_QNCT_TIER2_CD = QNCT_TIER2_CD AND QNDF_TYPE_QNCT_TIER1_CD = QNCT_TIER1_CD 
				LEFT JOIN TDWHORDR ON QNOT_ORDR_NO = ORDR_NO 
				LEFT JOIN TDWHWBSE ON ORDR_WBSE_ID = WBSE_ID
				LEFT JOIN TDWHQNTK ON QNTK_QNOT_NO = QNOT_NO AND QNTK_QNDF_NO = QNDF_NO
				LEFT JOIN TDWHQNDT ON QNDT_QNOT_NO = QNOT_NO AND QNDT_QNDF_NO = QNDF_NO
				LEFT JOIN TDWHGWBS ON WBSE_ID = GWBS_WBSE_ID
				LEFT JOIN TDWHPART PART1 ON QNOT_PART_NO = PART1.PART_NO
				LEFT JOIN TDWHPART PART2 ON QNDF_COMP_PART_NO = PART2.PART_NO

			WHERE
				QNOT_CREATED_DT >= SYSDATE - 1100
				AND (QNOT_TYP LIKE ''%Q3%'' or QNOT_TYP LIKE ''%F3%'' or QNOT_TYP LIKE ''%Z5%'')
				AND QNOT_PLNT_ID LIKE ''%P001%''
				And ((QNTK_QNCT_TIER2_CD like ''%PRDISP%'' and QNTK_ACTIVE_IND like ''%Y%'') or QNTK_QNCT_TIER2_CD is null)

			GROUP BY
				QNOT_PLNT_ID, QNOT_TYP, QNOT_NO, QNDF_NO, QNOT_CREATED_DT, QNOT_ACT_END_DT,QNOT_EMPL_ID, QNOT_PART_NO, PART1.PART_DESC,
				QNOT_ORDR_NO, QNOT_SPRT_SER_NO, WBSE_CD, WBSE_DESC, QNOT_QNCT_TIER3_CD, QNCT_TIER2_DESC, QNDF_TYPE_QNCT_TIER3_CD, QNCT_TIER3_DESC, 
				QNDF_DESC, QNDF_COMP_PART_NO, PART2.PART_DESC, QNDF_SPRT_SER_NO , WCTR_CD, WCTR_DESC, WCTR_WCCT_ID,
				OROP_ID, OROP_LINE1_DESC, QNTK_NO, QNTK_COMPLETED_DT, QNTK_QNCT_TIER3_CD, QNDF_LOCN_QNCT_TIER3_CD, ORDR_SPRT_SER_NO,
				ORDR_OPER_COMPLETED_DT, ORDR_STAT, ORDR_OCAT_CD
			)

		LEFT JOIN CDAS.TDWHNOTE ON QNOT_NO = NOTE_QNOT_NO AND QNDF_NO = NOTE_QNDF_NO 

		WHERE NOTE_QNDC_NO not like ''%0%'' or NOTE_QNDC_NO is null
		')