SELECT 
MOOP_PART_NO,
RTGO_NO,
MOOP_WCTR_CD,
RTGO_LINE1_DESC,
MOOP_CCTR_ID,
MOOP_TYP,
MOOP_PERFORM_INDEX_RT,
MOOP_SCHED_EXEC_START_DT,
MOOP_ADJ_EARN_RUN_HRS,
MOOP_ADJ_EARN_SETUP_HRS,
MOOP_ADJ_STD_RUN_HRS,
MOOP_ADJ_STD_SETUP_HRS,
MOOP_ACTUAL_HRS,
MOOP_STD_RUN_HRS,    
MOOP_STD_SETUP_HRS,
RTGO_STD_SETUP_RT,
RTGO_STD_RUN_RT


FROM 
TDWHMOOP LEFT JOIN TDWHRTGO on moop_rtgg_id = rtgo_rtgg_id and moop_rtgo_id = rtgo_id and moop_rtng_id = rtgo_rtng_id 
AND MOOP_ORDER_SCHED_START_DT >= '01-MAY-19'
