Select

ORDR_PART_NO,
OROP_ID,
WCTR_CD,
OROP_LINE1_DESC,
TRIM(LEADING 0 FROM ORDR_NO),
TRIM(leading 0 from ORDR_SPRT_SER_NO),
ORDR_STAT,
ORDR_OCAT_CD,
ILOE_PELE_CD,
ILOE_PELE_DESC,
ILOE_EVALUATION_CD,
ILOE_FAILED_QTY,
OROP_STAT,
OROP_ACT_COMPLETED_DTM


From
TDWHORDR INNER JOIN TDWHOROP ON (ORDR_RTG_NO = OROP_ORDR_RTG_NO)   
          INNER JOIN TDWHILOE ON (iloe_ordr_rtg_no = orop_ordr_rtg_no and iloe_orop_no = orop_no)
          INNER JOIN TDWHWCTR ON (OROP_WCTR_NO = WCTR_NO)
;
